language: python
python:
  - "3.7.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
  - pip install -r requirements_gpu.txt
  - pip install .
# command to run tests
script: python3 tests/download_images.py && pytest